name: GitHub CI

on:
  push:
    branches: ['**']
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linux:
    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    env:
      CC: ${{ matrix.compiler }}
      GCC_VER: 14
      CLANG_VER: 21
      TEST: test
      SRCDIR: ./src
      LEAK_CFLAGS: -DEXITFREE
      LOG_DIR: ${{ github.workspace }}/logs
      TERM: xterm
      DISPLAY: ':99'
      DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        features: [huge]
        compiler: [gcc]
        extra: [[]]
        # Only use non-native architecture when features != huge.
        # features=huge tries to install python3-dev, which fails to install
        # for the non-native architecture.
        architecture: [native]
        include:
          - features: huge
            shadow: ./src/shadow
            compiler: gcc
            architecture: i386

    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v5

      - name: Check Filelist (for packaging)
        run: |
          # If any files in the repository are not listed in Filelist this will
          # exit with an error code and list the missing entries.
          make -f ci/unlisted.make

      - name: Check hlgroups (are any new hlgroups added, but not handled in highlight.c)
        run: |
          # If any highlight groups have been documented, but not handled in
          # highlight.c, nor listed as 'intentionally left out' in hlgroups.ignore,
          # exit with an error code and list the missing entries.
          make -C ci -f hlgroups.make

      - run: sudo dpkg --add-architecture i386
        if: matrix.architecture == 'i386'

      - name: Uninstall snap
        run: |
          sudo bash ci/remove_snap.sh

      - name: Enable debug packages
        run: |
          # Some of the ASAN suppressions are in libraries linked with dlopen
          # and symbolization of them requires these debug packages.
          sudo apt install ubuntu-dbgsym-keyring
          sudo cp ci/ddebs.list /etc/apt/sources.list.d/ddebs.list
          sudo cp ci/pinned-pkgs /etc/apt/preferences.d/pinned-pkgs

      - name: Install packages
        run: |
          # This is added by default, and it is often broken, but we don't need anything from it
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          PKGS=( \
            gettext \
            x11-utils \
            labwc \
            wl-clipboard \
            wayland-utils \
            libgtk-3-dev:${{ matrix.architecture }} \
            libgtk-3-bin:${{ matrix.architecture }} \
            desktop-file-utils \
            libc6-dbgsym:${{ matrix.architecture }} \
            libtool-bin \
            libncurses-dev:${{ matrix.architecture }} \
            libxt-dev:${{ matrix.architecture }} \
            libegl-mesa0:${{ matrix.architecture }} \
            libegl1:${{ matrix.architecture }} \
            libegl1-mesa-dev:${{ matrix.architecture }} \
            libepoxy-dev:${{ matrix.architecture }} \
            libwayland-egl1:${{ matrix.architecture }} \
            libwayland-client0:${{ matrix.architecture }} \
            libwayland-cursor0:${{ matrix.architecture }} \
            locales-all \
            software-properties-common \
          )
          if ${{ contains(matrix.extra, 'asan') }} && ${{ contains(matrix.architecture, 'native') }}; then
          PKGS+=( \
            libepoxy0-dbgsym:${{ matrix.architecture }} \
            libxdamage1-dbgsym:${{ matrix.architecture }} \
            libxcb1-dbgsym:${{ matrix.architecture }} \
            libgtk-3-bin-dbgsym:${{ matrix.architecture }} \
            libgtk-3-0t64-dbgsym:${{ matrix.architecture }} \
            libglib2.0-0t64-dbgsym:${{ matrix.architecture }} \
            libglib2.0-bin-dbgsym:${{ matrix.architecture }} \
            libglib2.0-dev-bin-dbgsym:${{ matrix.architecture }} \
          )
          fi
          if ${{ matrix.features == 'huge' }}; then
            if ${{ matrix.architecture == 'i386' }}; then
              PKGS+=( \
                autoconf \
                gdb \
                libsodium-dev:${{ matrix.architecture }} \
                libattr1-dev:${{ matrix.architecture }} \
                libcanberra-dev:${{ matrix.architecture }}
              )
            else
              LUA_VER=${{ matrix.lua_ver || '5.4' }}
              PKGS+=( \
                autoconf \
                gdb \
                lcov \
                libcanberra-dev \
                libperl-dev \
                python3-dev \
                liblua${LUA_VER}-dev \
                lua${LUA_VER} \
                ruby-dev \
                tcl-dev \
                cscope \
                libsodium-dev \
                attr \
                libattr1-dev
              )
            fi
          fi
          sudo apt-get update && sudo apt-get upgrade -y --allow-downgrades && sudo apt-get install -y --allow-downgrades "${PKGS[@]}"

      - name: Install gcc-${{ env.GCC_VER }}
        if:  matrix.compiler == 'gcc'
        run: |
          # ubuntu-toolchain-r/test PPA for gcc-13 compiler
          # disabled because the installation failed, causing test failures
          # sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y gcc-${{ env.GCC_VER }}:${{ matrix.architecture }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_VER }} 100
          sudo update-alternatives --set gcc /usr/bin/gcc-${{ env.GCC_VER }}

      - name: Install clang-${{ env.CLANG_VER }}
        if: matrix.compiler == 'clang'
        run: |
          . /etc/lsb-release
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/llvm-archive-keyring.gpg > /dev/null
          echo "Types: deb
          URIs: https://apt.llvm.org/${DISTRIB_CODENAME}/
          Suites: llvm-toolchain-${DISTRIB_CODENAME}-${{ env.CLANG_VER }}
          Components: main
          Signed-By: /usr/share/keyrings/llvm-archive-keyring.gpg" | sudo tee /etc/apt/sources.list.d/llvm-toolchain.sources > /dev/null
          sudo apt-get update -y
          sudo apt-get install -y clang-${{ env.CLANG_VER }} llvm-${{ env.CLANG_VER }}
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ env.CLANG_VER }} 100
          sudo update-alternatives --set clang /usr/bin/clang-${{ env.CLANG_VER }}
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-${{ env.CLANG_VER }} 100
          sudo update-alternatives --install /usr/bin/asan_symbolize asan_symbolize /usr/bin/asan_symbolize-${{ env.CLANG_VER }} 100

      - name: Set up environment
        run: |
          mkdir -p "${LOG_DIR}"
          mkdir -p "${HOME}/bin"
          echo "${HOME}/bin" >> $GITHUB_PATH
          (
          echo "LINUX_VERSION=$(uname -r)"
          echo "NPROC=$(getconf _NPROCESSORS_ONLN)"
          echo "TMPDIR=$(mktemp -d -p /tmp)"
          echo "TEST_FILTER=termdebug"

          case "${{ matrix.features }}" in
          tiny)
            echo "TEST=testtiny"
            if ${{ contains(matrix.extra, 'nogui') }}; then
              CONFOPT="--disable-gui"
            fi
            ;;
          normal)
            ;;
          huge)
            echo "TEST=scripttests test_libvterm indenttest syntaxtest"
            INTERFACE=${{ matrix.interface || 'yes' }}
            if ${{ matrix.python3 == 'stable-abi' }}; then
              PYTHON3_CONFOPT="--with-python3-stable-abi=3.8"
            fi
            if ${{ matrix.architecture != 'i386' }}; then
              # The ubuntu-24.04 CI runner does not provide a python2 package.
              CONFOPT="--enable-perlinterp=${INTERFACE} --enable-pythoninterp=no --enable-python3interp=${INTERFACE} --enable-rubyinterp=${INTERFACE} --enable-luainterp=${INTERFACE} --enable-tclinterp=${INTERFACE} ${PYTHON3_CONFOPT}"
            fi
            ;;
          esac

          if ${{ contains(matrix.extra, 'no_x11') }}; then
            CONFOPT="${CONFOPT} --without-x --disable-gui"
          fi
          if ${{ contains(matrix.extra, 'socketserver') }}; then
            CONFOPT="${CONFOPT} --enable-socketserver"
          fi
          if ${{ matrix.coverage == true }}; then
            CFLAGS="${CFLAGS} --coverage -DUSE_GCOV_FLUSH"
            echo "LDFLAGS=--coverage"
          fi
          if ${{ contains(matrix.extra, 'uchar') }}; then
            CFLAGS="${CFLAGS} -funsigned-char"
          fi
          if ${{ contains(matrix.extra, 'testgui') }}; then
            echo "TEST=-C src testgui"
          fi
          if ${{ contains(matrix.extra, 'unittests') }}; then
            echo "TEST=unittests"
          fi
          if ${{ contains(matrix.extra, 'asan') }}; then
            echo "SANITIZER_CFLAGS=-g -O0 -DABORT_ON_INTERNAL_ERROR -DEXITFREE -fsanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer"
            echo "ASAN_OPTIONS=print_stacktrace=1:log_path=${LOG_DIR}/asan"
            echo "UBSAN_OPTIONS=print_stacktrace=1:log_path=${LOG_DIR}/ubsan"
            echo "LSAN_OPTIONS=suppressions=${GITHUB_WORKSPACE}/src/testdir/lsan-suppress.txt"
          fi
          if ${{ contains(matrix.extra, 'vimtags') }}; then
            echo "TEST=-C runtime/doc vimtags VIMEXE=../../${SRCDIR}/vim"
          fi
          echo "CFLAGS=${CFLAGS}"
          echo "CONFOPT=${CONFOPT}"
          # Disables GTK attempt to integrate with the accessibility service that does run in CI.
          echo "NO_AT_BRIDGE=1"
          ) >> $GITHUB_ENV

      - name: Set up system
        run: |
          if [[ ${CC} = clang ]]; then
            # Use llvm-cov instead of gcov when compiler is clang.
            ln -fs /usr/bin/llvm-cov ${HOME}/bin/gcov
          fi
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
          sudo usermod -a -G audio "${USER}"
          sudo bash ci/setup-xvfb.sh

      - name: Check autoconf
        if: contains(matrix.extra, 'unittests')
        run: |
          make -C src autoconf

      - name: Set up shadow dir
        if: matrix.shadow
        run: |
          make -C src shadow
          echo "SRCDIR=${{ matrix.shadow }}" >> $GITHUB_ENV
          echo "SHADOWOPT=-C ${{ matrix.shadow }}" >> $GITHUB_ENV

      - name: Configure
        run: |
          ./configure --with-features=${{ matrix.features }} ${CONFOPT} --enable-fail-if-missing
          # Append various warning flags to CFLAGS.
          sed -i -f ci/config.mk.sed ${SRCDIR}/auto/config.mk
          sed -i -f ci/config.mk.${CC}.sed ${SRCDIR}/auto/config.mk
          if [[ ${CC} = clang ]]; then
            # Suppress some warnings produced by clang 12 and later.
            sed -i -f ci/config.mk.clang-12.sed ${SRCDIR}/auto/config.mk
          fi

      - name: Build
        if: (!contains(matrix.extra, 'unittests'))
        run: |
          make ${SHADOWOPT} -j${NPROC}

      - name: Test
        timeout-minutes: 30
        run: |
          make ${SHADOWOPT} ${TEST}

      # Enable to debug failing tests live and ssh into the CI runners
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      - if: ${{ !cancelled() }}
        uses: ./.github/actions/test_artifacts

      - name: Vim tags
        if: contains(matrix.extra, 'vimtags')
        run: |
          # This will exit with an error code if the generated vim tags differs from source.
          (
            cd runtime/doc
            git diff --exit-code -- tags
            make html; rm *.html tags.ref;
            test -f errors.log && exit 3;
            true
          )

      - name: Generate gcov files
        if: matrix.coverage
        run: |
          cd "${SRCDIR}"
          find . -type f -name '*.gcno' -exec gcov -pb {} + || true

      - name: Codecov
        timeout-minutes: 20
        if: matrix.coverage
        uses: codecov/codecov-action@v5
        with:
          flags: linux,${{ matrix.features }}-${{ matrix.compiler }}-${{ join(matrix.extra, '-') }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: ASan logs
        if: contains(matrix.extra, 'asan') && !cancelled()
        run: |
          for f in $(grep -lR '#[[:digit:]]* *0x[[:xdigit:]]*' "${LOG_DIR}"); do
            echo "$f"
            asan_symbolize -l "$f"
            false # in order to fail a job
          done
